name: drone_assist
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  chopper: ^4.0.6

  cupertino_icons: ^1.0.2
  vrouter: ^1.2.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.2.0
  chopper_generator: ^4.0.6

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
